#!/bin/bash

# Link :  https://github.com/orchardup/docker-mysql

# PARAMETERS
#$1 container name

# Arguments verification
if [ $# -ne 1 ]; then
    echo "ERROR : One argument expected --> Container name"
    exit 65
fi

echo "Create and run $1 container ..."
ROOT_PWD=admin
DB=test
USER=testuser
USER_PWD=testpwd
ARGS=--skip-name-resolve
sudo docker run -d -p 3306:3306 --name $1 -e MYSQL_ROOT_PASSWORD=$ROOT_PWD -e MYSQL_DATABASE=$DB -e MYSQL_USER=$USER -e MYSQL_PASSWORD=$USER_PWD  -e MYSQLD_ARGS=$ARGS  orchardup/mysql

